input {
    kb_layout = us,ru
    kb_options = grp:lalt_lshift_toggle
    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    repeat_delay = 250
    repeat_rate = 35
}
